version: '3.7'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4572-4581:4572-4581"
      - "8080:8080"
    environment:
      SERVICES: "sqs,sns,s3,cloudformation"
      LOCALSTACK_HOSTNAME: "ec2-13-126-67-188.ap-south-1.compute.amazonaws.com"
      PORT_WEB_UI: "8080"
      DEBUG: "true"
      DEFAULT_REGION: "ap-south-1"
    volumes:
      - ~/tmp/localstack:/tmp/localstack